# Generated by Django 5.1 on 2024-08-30 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_excerpt'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, to='blog.tag'),
        ),
        migrations.AlterField(
            model_name='post',
            name='excerpt',
            field=models.TextField(default='', max_length=255),
        ),
    ]
